# Generated by Django 5.2.3 on 2025-07-04 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('nascionalidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='livro',
            name='autor_livro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.autor'),
            preserve_default=False,
        ),
    ]
